version: '3.8'

services:
  web:
    build: ./
    command: python3 -m uvicorn jokes_api.main:app --reload --host 0.0.0.0
    ports:
      - "8081:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://fastapi_squad:fastapi_squad@db:5432/fastapi_squad
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5435:5432'
    environment:
      - POSTGRES_USER=fastapi_squad
      - POSTGRES_PASSWORD=fastapi_squad
      - POSTGRES_DB=fastapi_squad
volumes:
  postgres_data:
